### PR TITLE
Fix cromwell slurm config

### PR DESCRIPTION
**Pull request by nathanthorpe**
Redo cromwell config.

- Error out if non dockerized task
- Fix sbatch command and make more clean
- Add s3 filesystem

### CODE REVIEW

**Comment by nathanthorpe** [comment]
Error

```
[2024-11-27 00:11:31,88] [error] Error parsing generated wdl:
```

Cromwell just hangs

**Review by sminot — APPROVED** [review]
Wow

**Comment by sminot** [comment]
Why isn’t this just in the headnode?

**Comment by sminot** [comment]
Oh right, it’s cluster specific

**Pull request merged**
